import { NextResponse } from 'next/server';
import { Partido } from '@/types'; 

export async function GET() {
  const partidos: Partido[] = [
    {
      id: '1',
      rival: 'Millonarios',
      escudoRival:'/escudos/Internacionales/millonarios.png',
      fecha: '2026-01-14',
      resultado: '0-0',
      estado: 'Empate',
      condicion: 'Local',
      goleadores: [],
      competicion: 'Amistoso',
      formacion: {
        esquema: "4-3-3",
        titulares: ['marchesin', 'blanco', 'costa', 'di_lollo', 'barinaga', 'delgado', 'paredes', 'ander', 'zeballos', 'merentiel', 'aguirre'],
        suplentes: []
      },
      estadisticas: {
        TotalRematesBoca: 17,
        TotalRematesRival: 4,
        RematesAlArcoBoca: 6,
        RematesAlArcoRival: 1,
        PosesionBoca: 62,
        PosesionRival: 38,
        AtaquesBoca: 47,
        AtaquesRival: 32,
        SaquesDeFaltaBoca: 13,
        SaquesDeFaltaRival: 12,
        SaquesDeEsquinaBoca: 9,
        SaquesDeEsquinaRival: 0,
        FueraDeJuegoBoca: 3,
        FueraDeJuegoRival: 2,
        FaltasBoca: 12,
        FaltasRival: 13,
        TarjetasAmarillasBoca: 1,
        TarjetasAmarillasRival: 3,
        TarjetasRojasBoca: 0,
        TarjetasRojasRival: 0
      }
    },
    {
      id: '2',
      rival: 'Olimpia',
      escudoRival:'/escudos/Internacionales/olimpia.png',
      fecha: '2026-01-18',
      resultado: '2-1',
      estado: 'Victoria',
      condicion: 'Local',
      goleadores: ['Velasco', 'Belmonte'],
      competicion: 'Amistoso',
      formacion: {
        esquema: "4-3-3",
        titulares: ['marchesin', 'braida', 'costa', 'di_lollo', 'barinaga', 'belmonte', 'paredes', 'ander', 'zeballos', 'merentiel', 'velasco'],
        suplentes: []
      },
      estadisticas: {
        TotalRematesBoca: 12,
        TotalRematesRival: 12,
        RematesAlArcoBoca: 3,
        RematesAlArcoRival: 3,
        PosesionBoca: 49,
        PosesionRival: 51,
        AtaquesBoca: 79,
        AtaquesRival: 71,
        SaquesDeFaltaBoca: 15,
        SaquesDeFaltaRival: 8,
        SaquesDeEsquinaBoca: 6,
        SaquesDeEsquinaRival: 3,
        FueraDeJuegoBoca: 0,
        FueraDeJuegoRival: 4,
        FaltasBoca: 8,
        FaltasRival: 15,
        TarjetasAmarillasBoca: 2,
        TarjetasAmarillasRival: 4,
        TarjetasRojasBoca: 0,
        TarjetasRojasRival: 0
      }
    },
    {
      id: '3',
      rival: 'Dep. Riestra',
      escudoRival: '/escudos/Argentinos/riestra.png',
      fecha: '2026-01-25',
      resultado: '1-0',
      estado: 'Victoria',
      condicion: 'Local',
      goleadores: ['Di Lollo'],
      competicion: 'Liga Profesional de Futbol',
      formacion: {
        esquema: "4-3-3",
        titulares: ['marchesin', 'blanco', 'costa', 'di_lollo', 'barinaga', 'belmonte', 'paredes', 'ander', 'zeballos', 'janson', 'velasco'],
        suplentes: []
      },
      estadisticas: {
        TotalRematesBoca: 19,
        TotalRematesRival: 6,
        RematesAlArcoBoca: 3,
        RematesAlArcoRival: 1,
        PosesionBoca: 80,
        PosesionRival: 20,
        AtaquesBoca: 86,
        AtaquesRival: 46,
        SaquesDeFaltaBoca: 19,
        SaquesDeFaltaRival: 8,
        SaquesDeEsquinaBoca: 12,
        SaquesDeEsquinaRival: 1,
        FueraDeJuegoBoca: 0,
        FueraDeJuegoRival: 2,
        FaltasBoca: 9,
        FaltasRival: 19,
        TarjetasAmarillasBoca: 1,
        TarjetasAmarillasRival: 5,
        TarjetasRojasBoca: 0,
        TarjetasRojasRival: 0
      }
    },
    {
      id: '4',
      rival: 'Estudiantes de La Plata',
      escudoRival: '/escudos/Argentinos/estudiantes.png',
      fecha: '2026-01-28',
      resultado: '2-1',
      estado: 'Derrota',
      condicion: 'Visitante',
      goleadores: ['Zeballos'],
      competicion: 'Liga Profesional de Futbol',
      formacion: {
        esquema: "4-3-3",
        titulares: ['marchesin', 'blanco', 'costa', 'di_lollo', 'barinaga', 'alarcon', 'paredes', 'belmonte', 'zeballos', 'zufiaurre', 'zenon'],
        suplentes: []
      },
      estadisticas: {
        TotalRematesBoca: 12,
        TotalRematesRival: 10,
        RematesAlArcoBoca: 7,
        RematesAlArcoRival: 3,
        PosesionBoca: 34,
        PosesionRival: 66,
        AtaquesBoca: 38,
        AtaquesRival: 43,
        SaquesDeFaltaBoca: 8,
        SaquesDeFaltaRival: 14,
        SaquesDeEsquinaBoca: 5,
        SaquesDeEsquinaRival: 7,
        FueraDeJuegoBoca: 0,
        FueraDeJuegoRival: 4,
        FaltasBoca: 15,
        FaltasRival: 8,
        TarjetasAmarillasBoca: 2,
        TarjetasAmarillasRival: 1,
        TarjetasRojasBoca: 0,
        TarjetasRojasRival: 0
      }
    },
    {
      id: '5',
      rival: 'Newell\'s Old Boys',
      escudoRival: '/escudos/Argentinos/newells.png',
      fecha: '2026-02-01',
      resultado: '2-0',
      estado: 'Victoria',
      condicion: 'Local',
      goleadores: ['Blanco', 'Paredes (p)'],
      competicion: 'Liga Profesional de Futbol',
      formacion: {
        esquema: "4-3-3",
        titulares: ['marchesin', 'blanco', 'costa', 'di_lollo', 'barinaga', 'ander', 'paredes', 'ascacibar', 'zeballos', 'zufiaurre', 'gelini'],
        suplentes: []
      },
      estadisticas: {
        TotalRematesBoca: 8,
        TotalRematesRival: 6,
        RematesAlArcoBoca: 5,
        RematesAlArcoRival: 1,
        PosesionBoca: 60,
        PosesionRival: 40,
        AtaquesBoca: 36,
        AtaquesRival: 38,
        SaquesDeFaltaBoca: 23,
        SaquesDeFaltaRival: 13,
        SaquesDeEsquinaBoca: 2,
        SaquesDeEsquinaRival: 1,
        FueraDeJuegoBoca: 1,
        FueraDeJuegoRival: 0,
        FaltasBoca: 15,
        FaltasRival: 23,
        TarjetasAmarillasBoca: 3,
        TarjetasAmarillasRival: 3,
        TarjetasRojasBoca: 0,
        TarjetasRojasRival: 0
      }
    },
    {
      id: '6',
      rival: 'Vélez Sarsfield',
      escudoRival: '/escudos/Argentinos/velez.png',
      fecha: '2026-02-08',
      resultado: '2-1',
      estado: 'Derrota',
      condicion: 'Visitante',
      goleadores: ['Zufiaurre'],
      competicion: 'Liga Profesional de Futbol',
      formacion: {
        esquema: "4-3-3",
        titulares: ['marchesin', 'blanco', 'costa', 'di_lollo', 'barinaga', 'paredes', 'delgado', 'ascacibar', 'zenon', 'merentiel', 'gelini'],
        suplentes: []
      },
      estadisticas: {
        TotalRematesBoca: 15,
        TotalRematesRival: 9,
        RematesAlArcoBoca: 4,
        RematesAlArcoRival: 3,
        PosesionBoca: 50,
        PosesionRival: 50,
        AtaquesBoca: 104,
        AtaquesRival: 87,
        SaquesDeFaltaBoca: 10,
        SaquesDeFaltaRival: 11,
        SaquesDeEsquinaBoca: 2,
        SaquesDeEsquinaRival: 7,
        FueraDeJuegoBoca: 1,
        FueraDeJuegoRival: 2,
        FaltasBoca: 11,
        FaltasRival: 10,
        TarjetasAmarillasBoca: 0,
        TarjetasAmarillasRival: 1,
        TarjetasRojasBoca: 0,
        TarjetasRojasRival: 0
      }
    },
    {
      id: '7',
      rival: 'Platense',
      escudoRival: '/escudos/Argentinos/platense.png',
      fecha: '2026-02-15',
      resultado: '0-0',
      estado: 'Empate',
      condicion: 'Local',
      goleadores: [],
      competicion: 'Liga Profesional de Futbol',
      formacion: {
        esquema: "4-3-3",
        titulares: ['marchesin', 'blanco', 'costa', 'di_lollo', 'barinaga', 'alarcon', 'paredes', 'ascacibar', 'janson', 'merentiel', 'romero'],
        suplentes: []
      },
      estadisticas: {
        TotalRematesBoca: 10,
        TotalRematesRival: 14,
        RematesAlArcoBoca: 3,
        RematesAlArcoRival: 1,
        PosesionBoca: 63,
        PosesionRival: 37,
        AtaquesBoca: 81,
        AtaquesRival: 69,
        SaquesDeFaltaBoca: 12,
        SaquesDeFaltaRival: 6,
        SaquesDeEsquinaBoca: 1,
        SaquesDeEsquinaRival: 2,
        FueraDeJuegoBoca: 3,
        FueraDeJuegoRival: 1,
        FaltasBoca: 6,
        FaltasRival: 12,
        TarjetasAmarillasBoca: 1,
        TarjetasAmarillasRival: 1,
        TarjetasRojasBoca: 0,
        TarjetasRojasRival: 0
      }
    }
  ];

  return NextResponse.json(partidos);
}